export const db = [
  {
    name: {
      common: "Uzbekistan",
      official: "Republic of Uzbekistan",
      nativeName: {
        rus: { official: "Республика Узбекистан", common: "Узбекистан" },
        uzb: {
          official: "O'zbekiston Respublikasi",
          common: "O‘zbekiston",
        },
      },
    },
    tld: [".uz"],
    cca2: "UZ",
    ccn3: "860",
    cca3: "UZB",
    cioc: "UZB",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { UZS: { name: "Uzbekistani soʻm", symbol: "so'm" } },
    idd: { root: "+9", suffixes: ["98"] },
    capital: ["Tashkent"],
    altSpellings: [
      "UZ",
      "Republic of Uzbekistan",
      "O‘zbekiston Respublikasi",
      "Ўзбекистон Республикаси",
    ],
    region: "Asia",
    subregion: "Central Asia",
    languages: { rus: "Russian", uzb: "Uzbek" },
    translations: {
      ara: { official: "جمهورية أوزباكستان", common: "أوزباكستان" },
      bre: { official: "Republik Ouzbekistan", common: "Ouzbekistan" },
      ces: { official: "Republika Uzbekistán", common: "Uzbekistán" },
      cym: { official: "Republic of Uzbekistan", common: "Uzbekistan" },
      deu: { official: "Republik Usbekistan", common: "Usbekistan" },
      est: { official: "Usbekistani Vabariik", common: "Usbekistan" },
      fin: { official: "Uzbekistanin tasavalta", common: "Uzbekistan" },
      fra: {
        official: "République d'Ouzbékistan",
        common: "Ouzbékistan",
      },
      hrv: { official: "Republika Uzbekistan", common: "Uzbekistan" },
      hun: { official: "Üzbég Köztársaság", common: "Üzbegisztán" },
      ita: { official: "Repubblica di Uzbekistan", common: "Uzbekistan" },
      jpn: { official: "ウズベキスタン共和国", common: "ウズベキスタン" },
      kor: { official: "우즈베키스탄 공화국", common: "우즈베키스탄" },
      nld: { official: "Republiek Oezbekistan", common: "Oezbekistan" },
      per: { official: "جمهوری ازبکستان", common: "ازبکستان" },
      pol: { official: "Republika Uzbekistanu", common: "Uzbekistan" },
      por: {
        official: "República do Usbequistão",
        common: "Uzbequistão",
      },
      rus: { official: "Республика Узбекистан", common: "Узбекистан" },
      slk: { official: "Uzbecká republika", common: "Uzbekistan" },
      spa: { official: "República de Uzbekistán", common: "Uzbekistán" },
      srp: { official: "Република Узбекистан", common: "Узбекистан" },
      swe: { official: "Republiken Uzbekistan", common: "Uzbekistan" },
      tur: { official: "Özbekistan Cumhuriyeti", common: "Özbekistan" },
      urd: { official: "جمہوریہ ازبکستان", common: "ازبکستان" },
      zho: { official: "乌兹别克斯坦共和国", common: "乌兹别克斯坦" },
    },
    latlng: [41.0, 64.0],
    landlocked: true,
    borders: ["AFG", "KAZ", "KGZ", "TJK", "TKM"],
    area: 447400.0,
    demonyms: {
      eng: { f: "Uzbekistani", m: "Uzbekistani" },
      fra: { f: "Ouzbèke", m: "Ouzbèke" },
    },
    flag: "\uD83C\uDDFA\uD83C\uDDFF",
    maps: {
      googleMaps: "https://goo.gl/maps/AJpo6MjMx23qSWCz8",
      openStreetMaps: "https://www.openstreetmap.org/relation/196240",
    },
    population: 34232050,
    gini: { "2003": 35.3 },
    fifa: "UZB",
    car: { signs: ["UZ"], side: "right" },
    timezones: ["UTC+05:00"],
    continents: ["Asia"],
    flags: {
      png: "https://flagcdn.com/w320/uz.png",
      svg: "https://flagcdn.com/uz.svg",
      alt: "The flag of Uzbekistan is composed of three equal horizontal bands of turquoise, white with red top and bottom edges, and green. On the hoist side of the turquoise band is a fly-side facing white crescent and twelve five-pointed white stars arranged just outside the crescent opening in three rows comprising three, four and five stars.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/uz.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/uz.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [41.32, 69.25] },
    postalCode: { format: "######", regex: "^(\\d{6})$" },
  },
  {
    name: {
      common: "Austria",
      official: "Republic of Austria",
      nativeName: {
        bar: { official: "Republik Österreich", common: "Österreich" },
      },
    },
    tld: [".at"],
    cca2: "AT",
    ccn3: "040",
    cca3: "AUT",
    cioc: "AUT",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    idd: { root: "+4", suffixes: ["3"] },
    capital: ["Vienna"],
    altSpellings: ["AT", "Osterreich", "Oesterreich"],
    region: "Europe",
    subregion: "Central Europe",
    languages: { de: "German" },
    translations: {
      ara: { official: "جمهورية النمسا", common: "النمسا" },
      bre: { official: "Republik Aostria", common: "Aostria" },
      ces: { official: "Rakouská republika", common: "Rakousko" },
      cym: { official: "Gweriniaeth Awstria", common: "Awstria" },
      deu: { official: "Republik Österreich", common: "Österreich" },
      est: { official: "Austria Vabariik", common: "Austria" },
      fin: { official: "Itävallan tasavalta", common: "Itävalta" },
      fra: { official: "République d'Autriche", common: "Autriche" },
      hrv: { official: "Republika Austrija", common: "Austrija" },
      hun: { official: "Ausztria", common: "Ausztria" },
      ita: { official: "Repubblica d'Austria", common: "Austria" },
      jpn: { official: "オーストリア共和国", common: "オーストリア" },
      kor: { official: "오스트리아 공화국", common: "오스트리아" },
      nld: { official: "Republiek Oostenrijk", common: "Oostenrijk" },
      per: { official: "جمهوری اتریش", common: "اتریش" },
      pol: { official: "Republika Austrii", common: "Austria" },
      por: { official: "República da Áustria", common: "Áustria" },
      rus: { official: "Австрийская Республика", common: "Австрия" },
      slk: { official: "Rakúska republika", common: "Rakúsko" },
      spa: { official: "República de Austria", common: "Austria" },
      srp: { official: "Република Аустрија", common: "Аустрија" },
      swe: { official: "Republiken Österrike", common: "Österrike" },
      tur: { official: "Avusturya Cumhuriyeti", common: "Avusturya" },
      urd: { official: "جمہوریہ آسٹریا", common: "آسٹریا" },
      zho: { official: "奥地利共和国", common: "奥地利" },
    },
    latlng: [47.33333333, 13.33333333],
    landlocked: true,
    borders: ["CZE", "DEU", "HUN", "ITA", "LIE", "SVK", "SVN", "CHE"],
    area: 83871.0,
    demonyms: {
      eng: { f: "Austrian", m: "Austrian" },
      fra: { f: "Autrichienne", m: "Autrichien" },
    },
    flag: "\uD83C\uDDE6\uD83C\uDDF9",
    maps: {
      googleMaps: "https://goo.gl/maps/pCWpWQhznHyRzQcu9",
      openStreetMaps: "https://www.openstreetmap.org/relation/16239",
    },
    population: 8917205,
    gini: { "2018": 30.8 },
    fifa: "AUT",
    car: { signs: ["A"], side: "right" },
    timezones: ["UTC+01:00"],
    continents: ["Europe"],
    flags: {
      png: "https://flagcdn.com/w320/at.png",
      svg: "https://flagcdn.com/at.svg",
      alt: "The flag of Austria is composed of three equal horizontal bands of red, white and red.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/at.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/at.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [48.2, 16.37] },
    postalCode: { format: "####", regex: "^(\\d{4})$" },
  },
  {
    name: {
      common: "Sierra Leone",
      official: "Republic of Sierra Leone",
      nativeName: {
        eng: {
          official: "Republic of Sierra Leone",
          common: "Sierra Leone",
        },
      },
    },
    tld: [".sl"],
    cca2: "SL",
    ccn3: "694",
    cca3: "SLE",
    cioc: "SLE",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { SLL: { name: "Sierra Leonean leone", symbol: "Le" } },
    idd: { root: "+2", suffixes: ["32"] },
    capital: ["Freetown"],
    altSpellings: ["SL", "Republic of Sierra Leone"],
    region: "Africa",
    subregion: "Western Africa",
    languages: { eng: "English" },
    translations: {
      ara: { official: "جمهورية سيراليون", common: "سيراليون" },
      bre: { official: "Republik Sierra Leone", common: "Sierra Leone" },
      ces: { official: "Republika Sierra Leone", common: "Sierra Leone" },
      cym: {
        official: "Republic of Sierra Leone",
        common: "Sierra Leone",
      },
      deu: { official: "Republik Sierra Leone", common: "Sierra Leone" },
      est: { official: "Sierra Leone Vabariik", common: "Sierra Leone" },
      fin: {
        official: "Sierra Leonen tasavalta",
        common: "Sierra Leone",
      },
      fra: {
        official: "République de Sierra Leone",
        common: "Sierra Leone",
      },
      hrv: { official: "Republika Sijera Leone", common: "Sijera Leone" },
      hun: {
        official: "Sierra Leone Köztársaság",
        common: "Sierra Leone",
      },
      ita: {
        official: "Repubblica della Sierra Leone",
        common: "Sierra Leone",
      },
      jpn: { official: "シエラレオネ共和国", common: "シエラレオネ" },
      kor: { official: "시에라리온 공화국", common: "시에라리온" },
      nld: { official: "Republiek Sierra Leone", common: "Sierra Leone" },
      per: { official: "جمهوری سیرالئون", common: "سیرالئون" },
      pol: { official: "Sierra Leone", common: "Sierra Leone" },
      por: { official: "República da Serra Leoa", common: "Serra Leoa" },
      rus: {
        official: "Республика Сьерра-Леоне",
        common: "Сьерра-Леоне",
      },
      slk: {
        official: "Sierraleonská republika",
        common: "Sierra Leone",
      },
      spa: {
        official: "República de Sierra Leona",
        common: "Sierra Leone",
      },
      srp: { official: "Република Сијера Леоне", common: "Сијера Леоне" },
      swe: {
        official: "Republiken Sierra Leone",
        common: "Sierra Leone",
      },
      tur: {
        official: "Sierra Leone Cumhuriyeti",
        common: "Sierra Leone",
      },
      urd: { official: "جمہوریہ سیرالیون", common: "سیرالیون" },
      zho: { official: "塞拉利昂共和国", common: "塞拉利昂" },
    },
    latlng: [8.5, -11.5],
    landlocked: false,
    borders: ["GIN", "LBR"],
    area: 71740.0,
    demonyms: {
      eng: { f: "Sierra Leonean", m: "Sierra Leonean" },
      fra: { f: "Sierra-leonaise", m: "Sierra-leonais" },
    },
    flag: "\uD83C\uDDF8\uD83C\uDDF1",
    maps: {
      googleMaps: "https://goo.gl/maps/jhacar85oq9QaeKB7",
      openStreetMaps: "https://www.openstreetmap.org/relation/192777",
    },
    population: 7976985,
    gini: { "2018": 35.7 },
    fifa: "SLE",
    car: { signs: ["WAL"], side: "right" },
    timezones: ["UTC"],
    continents: ["Africa"],
    flags: {
      png: "https://flagcdn.com/w320/sl.png",
      svg: "https://flagcdn.com/sl.svg",
      alt: "The flag of Sierra Leone is composed of three equal horizontal bands of green, white and blue.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/sl.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/sl.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [8.48, -13.23] },
  },
  {
    name: {
      common: "Cocos (Keeling) Islands",
      official: "Territory of the Cocos (Keeling) Islands",
      nativeName: {
        eng: {
          official: "Territory of the Cocos (Keeling) Islands",
          common: "Cocos (Keeling) Islands",
        },
      },
    },
    tld: [".cc"],
    cca2: "CC",
    ccn3: "166",
    cca3: "CCK",
    independent: false,
    status: "officially-assigned",
    unMember: false,
    currencies: { AUD: { name: "Australian dollar", symbol: "$" } },
    idd: { root: "+6", suffixes: ["1"] },
    capital: ["West Island"],
    altSpellings: ["CC", "Keeling Islands", "Cocos Islands"],
    region: "Oceania",
    subregion: "Australia and New Zealand",
    languages: { eng: "English" },
    translations: {
      ara: { official: "إقليم جزر كوكوس", common: "جزر كوكوس" },
      bre: {
        official: "Tiriad Inizi Cocos (Keeling)",
        common: "Inizi Cocos (Keeling)",
      },
      ces: { official: "Kokosové ostrovy", common: "Kokosové ostrovy" },
      cym: {
        official: "Tiriogaeth yr Ynysoedd Cocos (Keeling)",
        common: "Ynysoedd Cocos",
      },
      deu: {
        official: "Gebiet der Kokos- (Keeling-) Inseln",
        common: "Kokosinseln",
      },
      est: { official: "Kookossaarte ala", common: "Kookossaared" },
      fin: { official: "Kookossaaret", common: "Kookossaaret" },
      fra: {
        official: "Territoire des îles Cocos (Keeling)",
        common: "Îles Cocos",
      },
      hrv: {
        official: "Teritoriju Kokosovi (Keeling) Islands",
        common: "Kokosovi Otoci",
      },
      hun: { official: "Kókusz-szigetek", common: "Kókusz-szigetek" },
      ita: {
        official: "Territorio della (Keeling) Isole Cocos",
        common: "Isole Cocos e Keeling",
      },
      jpn: {
        official: "ココス諸島の領土",
        common: "ココス（キーリング）諸島",
      },
      kor: { official: "코코스 제도", common: "코코스 제도" },
      nld: {
        official: "Grondgebied van de Eilanden Cocos (Keeling )",
        common: "Cocoseilanden",
      },
      per: { official: "جزایر کوکوس", common: "جزایر کوکوس" },
      pol: { official: "Wyspy Kokosowe", common: "Wyspy Kokosowe" },
      por: {
        official: "Território dos Cocos (Keeling)",
        common: "Ilhas Cocos (Keeling)",
      },
      rus: {
        official: "Территория Кокосовые (Килинг) острова",
        common: "Кокосовые острова",
      },
      slk: { official: "Kokosové ostrovy", common: "Kokosové ostrovy" },
      spa: {
        official: "Territorio de los (Keeling) Islas Cocos",
        common: "Islas Cocos o Islas Keeling",
      },
      srp: {
        official: "Кокосова (Килинг) Острва",
        common: "Кокосова Острва",
      },
      swe: { official: "Kokosöarna", common: "Kokosöarna" },
      tur: {
        official: "Cocos (Keeling) Adaları",
        common: "Cocos (Keeling) Adaları",
      },
      urd: { official: "جزائر (کیلنگ) کوکوس", common: "جزائر کوکوس" },
      zho: { official: "科科斯", common: "科科斯" },
    },
    latlng: [12.1642, 96.871],
    landlocked: false,
    area: 14.0,
    demonyms: { eng: { f: "Cocos Islander", m: "Cocos Islander" } },
    flag: "\uD83C\uDDE8\uD83C\uDDE8",
    maps: {
      googleMaps: "https://goo.gl/maps/3eCdKVpVfMcZyKcK6",
      openStreetMaps: "https://www.openstreetmap.org/relation/82636",
    },
    population: 544,
    car: { signs: ["AUS"], side: "left" },
    timezones: ["UTC+06:30"],
    continents: ["Asia"],
    flags: {
      png: "https://flagcdn.com/w320/cc.png",
      svg: "https://flagcdn.com/cc.svg",
    },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [-12.17, 96.83] },
  },
  {
    name: {
      common: "Mauritania",
      official: "Islamic Republic of Mauritania",
      nativeName: {
        ara: {
          official: "الجمهورية الإسلامية الموريتانية",
          common: "موريتانيا",
        },
      },
    },
    tld: [".mr"],
    cca2: "MR",
    ccn3: "478",
    cca3: "MRT",
    cioc: "MTN",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { MRU: { name: "Mauritanian ouguiya", symbol: "UM" } },
    idd: { root: "+2", suffixes: ["22"] },
    capital: ["Nouakchott"],
    altSpellings: [
      "MR",
      "Islamic Republic of Mauritania",
      "al-Jumhūriyyah al-ʾIslāmiyyah al-Mūrītāniyyah",
    ],
    region: "Africa",
    subregion: "Western Africa",
    languages: { ara: "Arabic" },
    translations: {
      ara: {
        official: "الجمهورية الإسلامية الموريتانية",
        common: "موريتانيا",
      },
      bre: {
        official: "Republik islamek Maouritania",
        common: "Maouritania",
      },
      ces: {
        official: "Mauritánská islámská republika",
        common: "Mauritánie",
      },
      cym: {
        official: "Islamic Republic of Mauritania",
        common: "Mauritania",
      },
      deu: {
        official: "Islamische Republik Mauretanien",
        common: "Mauretanien",
      },
      est: {
        official: "Mauritaania Islamivabariik",
        common: "Mauritaania",
      },
      fin: {
        official: "Mauritanian islamilainen tasavalta",
        common: "Mauritania",
      },
      fra: {
        official: "République islamique de Mauritanie",
        common: "Mauritanie",
      },
      hrv: {
        official: "Islamska Republika Mauritanija",
        common: "Mauritanija",
      },
      hun: {
        official: "Mauritániai Iszlám Köztársaság",
        common: "Mauritánia",
      },
      ita: {
        official: "Repubblica islamica di Mauritania",
        common: "Mauritania",
      },
      jpn: {
        official: "モーリタニア·イスラム共和国",
        common: "モーリタニア",
      },
      kor: { official: "모리타니 이슬람 공화국", common: "모리타니" },
      nld: {
        official: "Islamitische Republiek Mauritanië",
        common: "Mauritanië",
      },
      per: { official: "جمهوری اسلامی موریتانی", common: "موریتانی" },
      pol: {
        official: "Islamska Republika Mauretańska",
        common: "Mauretania",
      },
      por: {
        official: "República Islâmica da Mauritânia",
        common: "Mauritânia",
      },
      rus: {
        official: "Исламская Республика Мавритания",
        common: "Мавритания",
      },
      slk: {
        official: "Mauritánska islamská republika",
        common: "Mauritánia",
      },
      spa: {
        official: "República Islámica de Mauritania",
        common: "Mauritania",
      },
      srp: {
        official: "Исламска Република Мауританија",
        common: "Мауританија",
      },
      swe: {
        official: "Islamiska republiken Mauretanien",
        common: "Mauretanien",
      },
      tur: {
        official: "Moritanya İslam Cumhuriyeti",
        common: "Moritanya",
      },
      urd: { official: "اسلامی جمہوریہ موریتانیہ", common: "موریتانیہ" },
      zho: { official: "毛里塔尼亚伊斯兰共和国", common: "毛里塔尼亚" },
    },
    latlng: [20.0, -12.0],
    landlocked: false,
    borders: ["DZA", "MLI", "SEN", "ESH"],
    area: 1030700.0,
    demonyms: {
      eng: { f: "Mauritanian", m: "Mauritanian" },
      fra: { f: "Mauritanienne", m: "Mauritanien" },
    },
    flag: "\uD83C\uDDF2\uD83C\uDDF7",
    maps: {
      googleMaps: "https://goo.gl/maps/im2MmQ5jFjzxWBks5",
      openStreetMaps: "https://www.openstreetmap.org/relation/192763",
    },
    population: 4649660,
    gini: { "2014": 32.6 },
    fifa: "MTN",
    car: { signs: ["RIM"], side: "right" },
    timezones: ["UTC"],
    continents: ["Africa"],
    flags: {
      png: "https://flagcdn.com/w320/mr.png",
      svg: "https://flagcdn.com/mr.svg",
      alt: "The flag of Mauritania has a green field with a thin red horizontal band at the top and bottom of the field. At the center of the field is a five-pointed yellow star above an upward facing yellow crescent.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/mr.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/mr.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [18.07, -15.97] },
  },
  {
    name: {
      common: "Israel",
      official: "State of Israel",
      nativeName: {
        ara: { official: "دولة إسرائيل", common: "إسرائيل" },
        heb: { official: "מדינת ישראל", common: "ישראל" },
      },
    },
    tld: [".il"],
    cca2: "IL",
    ccn3: "376",
    cca3: "ISR",
    cioc: "ISR",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { ILS: { name: "Israeli new shekel", symbol: "₪" } },
    idd: { root: "+9", suffixes: ["72"] },
    capital: ["Jerusalem"],
    altSpellings: ["IL", "State of Israel", "Medīnat Yisrā'el"],
    region: "Asia",
    subregion: "Western Asia",
    languages: { ara: "Arabic", heb: "Hebrew" },
    translations: {
      ara: { official: "دولة إسرائيل", common: "إسرائيل" },
      bre: { official: "Stad Israel", common: "Israel" },
      ces: { official: "Stát Izrael", common: "Izrael" },
      cym: { official: "State of Israel", common: "Israel" },
      deu: { official: "Staat Israel", common: "Israel" },
      est: { official: "Iisraeli Riik", common: "Iisrael" },
      fin: { official: "Israelin valtio", common: "Israel" },
      fra: { official: "État d'Israël", common: "Israël" },
      hrv: { official: "Država Izrael", common: "Izrael" },
      hun: { official: "Izrael", common: "Izrael" },
      ita: { official: "Stato di Israele", common: "Israele" },
      jpn: { official: "イスラエル国", common: "イスラエル" },
      kor: { official: "이스라엘국", common: "이스라엘" },
      nld: { official: "Staat Israël", common: "Israël" },
      per: { official: "فلسطين اشغالی", common: "فلسطين اشغالی" },
      pol: { official: "Państwo Izrael", common: "Izrael" },
      por: { official: "Estado de Israel", common: "Israel" },
      rus: { official: "Государство Израиль", common: "Израиль" },
      slk: { official: "Izraelský štát", common: "Izrael" },
      spa: { official: "Estado de Israel", common: "Israel" },
      srp: { official: "Држава Израел", common: "Израел" },
      swe: { official: "Staten Israel", common: "Israel" },
      tur: { official: "İsrail Devleti", common: "İsrail" },
      urd: { official: "ریاستِ اسرائیل", common: "اسرائیل" },
      zho: { official: "以色列国", common: "以色列" },
    },
    latlng: [31.47, 35.13],
    landlocked: false,
    borders: ["EGY", "JOR", "LBN", "PSE", "SYR"],
    area: 20770.0,
    demonyms: {
      eng: { f: "Israeli", m: "Israeli" },
      fra: { f: "Israélienne", m: "Israélien" },
    },
    flag: "\uD83C\uDDEE\uD83C\uDDF1",
    maps: {
      googleMaps: "https://goo.gl/maps/6UY1AH8XeafVwdC97",
      openStreetMaps: "https://www.openstreetmap.org/relation/1473946",
    },
    population: 9216900,
    gini: { "2016": 39.0 },
    fifa: "ISR",
    car: { signs: ["IL"], side: "right" },
    timezones: ["UTC+02:00"],
    continents: ["Asia"],
    flags: {
      png: "https://flagcdn.com/w320/il.png",
      svg: "https://flagcdn.com/il.svg",
      alt: "The flag of Israel has a white field with a blue hexagram — the Magen David — centered between two equal horizontal blue bands situated near the top and bottom edges of the field.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/il.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/il.svg",
    },
    startOfWeek: "sunday",
    capitalInfo: { latlng: [31.77, 35.23] },
    postalCode: { format: "#####", regex: "^(\\d{5})$" },
  },
  {
    name: {
      common: "Moldova",
      official: "Republic of Moldova",
      nativeName: {
        ron: { official: "Republica Moldova", common: "Moldova" },
      },
    },
    tld: [".md"],
    cca2: "MD",
    ccn3: "498",
    cca3: "MDA",
    cioc: "MDA",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { MDL: { name: "Moldovan leu", symbol: "L" } },
    idd: { root: "+3", suffixes: ["73"] },
    capital: ["Chișinău"],
    altSpellings: [
      "MD",
      "Moldova, Republic of",
      "Republic of Moldova",
      "Republica Moldova",
    ],
    region: "Europe",
    subregion: "Eastern Europe",
    languages: { ron: "Romanian" },
    translations: {
      ara: { official: "جمهورية مولدوڤا", common: "مولدوڤا" },
      bre: { official: "Republik Moldova", common: "Moldova" },
      ces: { official: "Moldavská republika", common: "Moldavsko" },
      cym: { official: "Republic of Moldova", common: "Moldova" },
      deu: { official: "Republik Moldau", common: "Moldawien" },
      est: { official: "Moldova Vabariik", common: "Moldova" },
      fin: { official: "Moldovan tasavalta", common: "Moldova" },
      fra: { official: "République de Moldavie", common: "Moldavie" },
      hrv: { official: "Moldavija", common: "Moldova" },
      hun: { official: "Moldovai Köztársaság", common: "Moldova" },
      ita: { official: "Repubblica di Moldova", common: "Moldavia" },
      jpn: { official: "モルドバ共和国", common: "モルドバ共和国" },
      kor: { official: "몰도바 공화국", common: "몰도바" },
      nld: { official: "Republiek Moldavië", common: "Moldavië" },
      per: { official: "جمهوری مولداوی", common: "مولداوی" },
      pol: { official: "Republika Mołdawii", common: "Mołdawia" },
      por: { official: "República da Moldávia", common: "Moldávia" },
      rus: { official: "Молдова", common: "Молдавия" },
      slk: { official: "Moldavská republika", common: "Moldavsko" },
      spa: { official: "República de Moldova", common: "Moldavia" },
      srp: { official: "Република Молдавија", common: "Молдавија" },
      swe: { official: "Republiken Moldavien", common: "Moldavien" },
      tur: { official: "Moldova Cumhuriyeti", common: "Moldova" },
      urd: { official: "جمہوریہ مالدووا", common: "مالدووا" },
      zho: { official: "摩尔多瓦共和国", common: "摩尔多瓦" },
    },
    latlng: [47.0, 29.0],
    landlocked: true,
    borders: ["ROU", "UKR"],
    area: 33846.0,
    demonyms: {
      eng: { f: "Moldovan", m: "Moldovan" },
      fra: { f: "Moldave", m: "Moldave" },
    },
    flag: "\uD83C\uDDF2\uD83C\uDDE9",
    maps: {
      googleMaps: "https://goo.gl/maps/JjmyUuULujnDeFPf7",
      openStreetMaps: "https://www.openstreetmap.org/relation/58974",
    },
    population: 2617820,
    gini: { "2018": 25.7 },
    fifa: "MDA",
    car: { signs: ["MD"], side: "right" },
    timezones: ["UTC+02:00"],
    continents: ["Europe"],
    flags: {
      png: "https://flagcdn.com/w320/md.png",
      svg: "https://flagcdn.com/md.svg",
      alt: "The flag of Moldova is composed of three equal vertical bands of blue, yellow and red, with the national coat of arms centered in the yellow band.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/md.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/md.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [47.01, 28.9] },
    postalCode: { format: "MD-####", regex: "^(?:MD)*(\\d{4})$" },
  },
  {
    name: {
      common: "Fiji",
      official: "Republic of Fiji",
      nativeName: {
        eng: { official: "Republic of Fiji", common: "Fiji" },
        fij: { official: "Matanitu Tugalala o Viti", common: "Viti" },
        hif: { official: "रिपब्लिक ऑफ फीजी", common: "फिजी" },
      },
    },
    tld: [".fj"],
    cca2: "FJ",
    ccn3: "242",
    cca3: "FJI",
    cioc: "FIJ",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { FJD: { name: "Fijian dollar", symbol: "$" } },
    idd: { root: "+6", suffixes: ["79"] },
    capital: ["Suva"],
    altSpellings: [
      "FJ",
      "Viti",
      "Republic of Fiji",
      "Matanitu ko Viti",
      "Fijī Gaṇarājya",
    ],
    region: "Oceania",
    subregion: "Melanesia",
    languages: { eng: "English", fij: "Fijian", hif: "Fiji Hindi" },
    translations: {
      ara: { official: "جمهورية جزر فيجي", common: "فيجي" },
      bre: { official: "Republik Fidji", common: "Fidji" },
      ces: { official: "Republika Fidžijských ostrovů", common: "Fidži" },
      cym: { official: "Republic of Fiji", common: "Fiji" },
      deu: { official: "Republik Fidschi", common: "Fidschi" },
      est: { official: "Fidži Vabariik", common: "Fidži" },
      fin: { official: "Fidžin tasavalta", common: "Fidži" },
      fra: { official: "République des Fidji", common: "Fidji" },
      hrv: { official: "Republika Fidži", common: "Fiđi" },
      hun: {
        official: "Fidzsi-szigeteki Köztársaság",
        common: "Fidzsi-szigetek",
      },
      ita: { official: "Repubblica di Figi", common: "Figi" },
      jpn: { official: "フィジー共和国", common: "フィジー" },
      kor: { official: "피지 공화국", common: "피지" },
      nld: { official: "Republiek Fiji", common: "Fiji" },
      per: { official: "جمهوری جزایر فیجی", common: "فیجی" },
      pol: { official: "Republika Fidżi", common: "Fidżi" },
      por: { official: "República de Fiji", common: "Fiji" },
      rus: { official: "Республика Фиджи", common: "Фиджи" },
      slk: { official: "Fiǆijská republika", common: "Fiǆi" },
      spa: { official: "República de Fiji", common: "Fiyi" },
      srp: { official: "Република Фиџи", common: "Фиџи" },
      swe: { official: "Republiken Fiji", common: "Fiji" },
      tur: { official: "Fiji Cumhuriyeti", common: "Fiji" },
      urd: { official: "جمہوریہ فجی", common: "فجی" },
      zho: { official: "斐济共和国", common: "斐济" },
    },
    latlng: [17.7134, 178.065],
    landlocked: false,
    area: 18272.0,
    demonyms: {
      eng: { f: "Fijian", m: "Fijian" },
      fra: { f: "Fidjienne", m: "Fidjien" },
    },
    flag: "\uD83C\uDDEB\uD83C\uDDEF",
    maps: {
      googleMaps: "https://goo.gl/maps/r9fhDqoLZdg1zmE99",
      openStreetMaps: "https://www.openstreetmap.org/relation/571747",
    },
    population: 896444,
    gini: { "2013": 36.7 },
    fifa: "FIJ",
    car: { signs: ["FJI"], side: "left" },
    timezones: ["UTC+12:00"],
    continents: ["Oceania"],
    flags: {
      png: "https://flagcdn.com/w320/fj.png",
      svg: "https://flagcdn.com/fj.svg",
      alt: "The flag of Fiji has a light blue field. It features the flag of the United Kingdom — the Union Jack — in the canton and the shield of the national coat of arms centered in the fly half.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/fj.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/fj.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [-18.13, 178.42] },
  },
  {
    name: {
      common: "Serbia",
      official: "Republic of Serbia",
      nativeName: {
        srp: { official: "Република Србија", common: "Србија" },
      },
    },
    tld: [".rs", ".срб"],
    cca2: "RS",
    ccn3: "688",
    cca3: "SRB",
    cioc: "SRB",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { RSD: { name: "Serbian dinar", symbol: "дин." } },
    idd: { root: "+3", suffixes: ["81"] },
    capital: ["Belgrade"],
    altSpellings: [
      "RS",
      "Srbija",
      "Republic of Serbia",
      "Република Србија",
      "Republika Srbija",
    ],
    region: "Europe",
    subregion: "Southeast Europe",
    languages: { srp: "Serbian" },
    translations: {
      ara: { official: "جمهورية صيربيا", common: "صيربيا" },
      bre: { official: "Republik Serbia", common: "Serbia" },
      ces: { official: "Srbská republika", common: "Srbsko" },
      cym: { official: "Republic of Serbia", common: "Serbia" },
      deu: { official: "Republik Serbien", common: "Serbien" },
      est: { official: "Serbia Vabariik", common: "Serbia" },
      fin: { official: "Serbian tasavalta", common: "Serbia" },
      fra: { official: "République de Serbie", common: "Serbie" },
      hrv: { official: "Republika Srbija", common: "Srbija" },
      hun: { official: "Szerb Köztársaság", common: "Szerbia" },
      ita: { official: "Repubblica di Serbia", common: "Serbia" },
      jpn: { official: "セルビア共和国", common: "セルビア" },
      kor: { official: "세르비아 공화국", common: "세르비아" },
      nld: { official: "Republiek Servië", common: "Servië" },
      per: { official: "جمهوری صربستان", common: "صربستان" },
      pol: { official: "Republika Serbii", common: "Serbia" },
      por: { official: "República da Sérvia", common: "Sérvia" },
      rus: { official: "Республика Сербия", common: "Сербия" },
      slk: { official: "Srbská republika", common: "Srbsko" },
      spa: { official: "República de Serbia", common: "Serbia" },
      srp: { official: "Република Србија", common: "Србија" },
      swe: { official: "Republiken Serbien", common: "Serbien" },
      tur: { official: "Sırbistan Cumhuriyeti", common: "Sırbistan" },
      urd: { official: "جمہوریہ سربیا", common: "سربیا" },
      zho: { official: "塞尔维亚共和国", common: "塞尔维亚" },
    },
    latlng: [44.0, 21.0],
    landlocked: true,
    borders: ["BIH", "BGR", "HRV", "HUN", "UNK", "MKD", "MNE", "ROU"],
    area: 88361.0,
    demonyms: {
      eng: { f: "Serbian", m: "Serbian" },
      fra: { f: "Serbe", m: "Serbe" },
    },
    flag: "\uD83C\uDDF7\uD83C\uDDF8",
    maps: {
      googleMaps: "https://goo.gl/maps/2Aqof7aV2Naq8YEK8",
      openStreetMaps: "https://www.openstreetmap.org/relation/1741311",
    },
    population: 6908224,
    gini: { "2017": 36.2 },
    fifa: "SRB",
    car: { signs: ["SRB"], side: "right" },
    timezones: ["UTC+01:00"],
    continents: ["Europe"],
    flags: {
      png: "https://flagcdn.com/w320/rs.png",
      svg: "https://flagcdn.com/rs.svg",
      alt: "The flag of Serbia is composed of three equal horizontal bands of red, blue and white. The coat of arms of Serbia is superimposed at the center of the field slightly towards the hoist side.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/rs.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/rs.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [44.83, 20.5] },
    postalCode: { format: "######", regex: "^(\\d{6})$" },
  },
  {
    name: {
      common: "Cameroon",
      official: "Republic of Cameroon",
      nativeName: {
        eng: { official: "Republic of Cameroon", common: "Cameroon" },
        fra: { official: "République du Cameroun", common: "Cameroun" },
      },
    },
    tld: [".cm"],
    cca2: "CM",
    ccn3: "120",
    cca3: "CMR",
    cioc: "CMR",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: {
      XAF: { name: "Central African CFA franc", symbol: "Fr" },
    },
    idd: { root: "+2", suffixes: ["37"] },
    capital: ["Yaoundé"],
    altSpellings: ["CM", "Republic of Cameroon", "République du Cameroun"],
    region: "Africa",
    subregion: "Middle Africa",
    languages: { eng: "English", fra: "French" },
    translations: {
      ara: { official: "جمهورية الكاميرون", common: "الكاميرون" },
      bre: { official: "Republik Kameroun", common: "Kameroun" },
      ces: { official: "Kamerunská republika", common: "Kamerun" },
      cym: { official: "Gweriniaeth Camerŵn", common: "Camerŵn" },
      deu: { official: "Republik Kamerun", common: "Kamerun" },
      est: { official: "Kameruni Vabariik", common: "Kamerun" },
      fin: { official: "Kamerunin tasavalta", common: "Kamerun" },
      fra: { official: "République du Cameroun", common: "Cameroun" },
      hrv: { official: "Republika Kamerun", common: "Kamerun" },
      hun: { official: "Kameruni Köztársaság", common: "Kamerun" },
      ita: { official: "Repubblica del Camerun", common: "Camerun" },
      jpn: { official: "カメルーン共和国", common: "カメルーン" },
      kor: { official: "카메룬 공화국", common: "카메룬" },
      nld: { official: "Republiek Kameroen", common: "Kameroen" },
      per: { official: "جمهوری کامِرون", common: "کامِرون" },
      pol: { official: "Republika Kamerunu", common: "Kamerun" },
      por: { official: "República dos Camarões", common: "Camarões" },
      rus: { official: "Республика Камерун", common: "Камерун" },
      slk: { official: "Kamerunská republika", common: "Kamerun" },
      spa: { official: "República de Camerún", common: "Camerún" },
      srp: { official: "Република Камерун", common: "Камерун" },
      swe: { official: "Republiken Kamerun", common: "Kamerun" },
      tur: { official: "Kamerun Cumhuriyeti", common: "Kamerun" },
      urd: { official: "جمہوریہ کیمرون", common: "کیمرون" },
      zho: { official: "喀麦隆共和国", common: "喀麦隆" },
    },
    latlng: [6.0, 12.0],
    landlocked: false,
    borders: ["CAF", "TCD", "COG", "GNQ", "GAB", "NGA"],
    area: 475442.0,
    demonyms: {
      eng: { f: "Cameroonian", m: "Cameroonian" },
      fra: { f: "Camerounaise", m: "Camerounais" },
    },
    flag: "\uD83C\uDDE8\uD83C\uDDF2",
    maps: {
      googleMaps: "https://goo.gl/maps/JqiipHgFboG3rBJh9",
      openStreetMaps: "https://www.openstreetmap.org/relation/192830",
    },
    population: 26545864,
    gini: { "2014": 46.6 },
    fifa: "CMR",
    car: { signs: ["CAM"], side: "right" },
    timezones: ["UTC+01:00"],
    continents: ["Africa"],
    flags: {
      png: "https://flagcdn.com/w320/cm.png",
      svg: "https://flagcdn.com/cm.svg",
      alt: "The flag of Cameroon is composed of three equal vertical bands of green, red and yellow, with a yellow five-pointed star in the center.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/cm.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/cm.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [3.85, 11.5] },
  },
  {
    name: {
      common: "Bahamas",
      official: "Commonwealth of the Bahamas",
      nativeName: {
        eng: {
          official: "Commonwealth of the Bahamas",
          common: "Bahamas",
        },
      },
    },
    tld: [".bs"],
    cca2: "BS",
    ccn3: "044",
    cca3: "BHS",
    cioc: "BAH",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: {
      BSD: { name: "Bahamian dollar", symbol: "$" },
      USD: { name: "United States dollar", symbol: "$" },
    },
    idd: { root: "+1", suffixes: ["242"] },
    capital: ["Nassau"],
    altSpellings: ["BS", "Commonwealth of the Bahamas"],
    region: "Americas",
    subregion: "Caribbean",
    languages: { eng: "English" },
    translations: {
      ara: { official: "كومنولث جزر البهاما", common: "باهاماس" },
      bre: { official: "Kenglad ar Bahamas", common: "Bahamas" },
      ces: { official: "Bahamské společenství", common: "Bahamy" },
      cym: { official: "Cymanwlad y Bahamas", common: "Bahamas" },
      deu: { official: "Commonwealth der Bahamas", common: "Bahamas" },
      est: { official: "Bahama Ühendus", common: "Bahama" },
      fin: { official: "Bahaman liittovaltio", common: "Bahamasaaret" },
      fra: { official: "Commonwealth des Bahamas", common: "Bahamas" },
      hrv: { official: "Zajednica Bahama", common: "Bahami" },
      hun: { official: "Bahamai Közösség", common: "Bahama-szigetek" },
      ita: { official: "Commonwealth delle Bahamas", common: "Bahamas" },
      jpn: { official: "バハマ", common: "バハマ" },
      kor: { official: "바하마 연방", common: "바하마" },
      nld: { official: "Gemenebest van de Bahama's", common: "Bahama’s" },
      per: { official: "قلمرو همسود باهاما", common: "باهاما" },
      pol: { official: "Bahamy", common: "Bahamy" },
      por: { official: "Comunidade das Bahamas", common: "Bahamas" },
      rus: {
        official: "Содружество Багамских Островов",
        common: "Багамские Острова",
      },
      slk: { official: "Bahamské spoločenstvo", common: "Bahamy" },
      spa: { official: "Commonwealth de las Bahamas", common: "Bahamas" },
      srp: { official: "Комонвелт Бахама", common: "Бахами" },
      swe: { official: "Samväldet Bahamas", common: "Bahamas" },
      tur: {
        official: "Bahama Milletler Topluluğu",
        common: "Bahamalar",
      },
      urd: { official: "دولتِ مشترکہ بہاماس", common: "بہاماس" },
      zho: { official: "巴哈马联邦", common: "巴哈马" },
    },
    latlng: [25.0343, -77.3963],
    landlocked: false,
    area: 13943.0,
    demonyms: {
      eng: { f: "Bahamian", m: "Bahamian" },
      fra: { f: "Bahamienne", m: "Bahamien" },
    },
    flag: "\uD83C\uDDE7\uD83C\uDDF8",
    maps: {
      googleMaps: "https://goo.gl/maps/1YzRs1BZrG8p8pmVA",
      openStreetMaps: "https://www.openstreetmap.org/relation/547469",
    },
    population: 393248,
    fifa: "BAH",
    car: { signs: ["BS"], side: "left" },
    timezones: ["UTC-05:00"],
    continents: ["North America"],
    flags: {
      png: "https://flagcdn.com/w320/bs.png",
      svg: "https://flagcdn.com/bs.svg",
      alt: "The flag of the Bahamas is composed of three equal horizontal bands of aquamarine, yellow and aquamarine, with a black equilateral triangle superimposed on the hoist side of the field. This triangle has its base on the hoist end and spans about one-third the width of the field.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/bs.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/bs.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [25.08, -77.35] },
  },
  {
    name: {
      common: "Nauru",
      official: "Republic of Nauru",
      nativeName: {
        eng: { official: "Republic of Nauru", common: "Nauru" },
        nau: { official: "Republic of Nauru", common: "Nauru" },
      },
    },
    tld: [".nr"],
    cca2: "NR",
    ccn3: "520",
    cca3: "NRU",
    cioc: "NRU",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { AUD: { name: "Australian dollar", symbol: "$" } },
    idd: { root: "+6", suffixes: ["74"] },
    capital: ["Yaren"],
    altSpellings: [
      "NR",
      "Naoero",
      "Pleasant Island",
      "Republic of Nauru",
      "Ripublik Naoero",
    ],
    region: "Oceania",
    subregion: "Micronesia",
    languages: { eng: "English", nau: "Nauru" },
    translations: {
      ara: { official: "جمهورية ناورو", common: "ناورو" },
      bre: { official: "Republik Nauru", common: "Nauru" },
      ces: { official: "Republika Nauru", common: "Nauru" },
      cym: { official: "Republic of Nauru", common: "Nauru" },
      deu: { official: "Republik Nauru", common: "Nauru" },
      est: { official: "Nauru Vabariik", common: "Nauru" },
      fin: { official: "Naurun tasavalta", common: "Nauru" },
      fra: { official: "République de Nauru", common: "Nauru" },
      hrv: { official: "Republika Nauru", common: "Nauru" },
      hun: { official: "Naurui Köztársaság", common: "Nauru" },
      ita: { official: "Repubblica di Nauru", common: "Nauru" },
      jpn: { official: "ナウル共和国", common: "ナウル" },
      kor: { official: "나우루 공화국", common: "나우루" },
      nld: { official: "Republiek Nauru", common: "Nauru" },
      per: { official: "جمهوری نائورو", common: "نائورو" },
      pol: { official: "Republika Nauru", common: "Nauru" },
      por: { official: "República de Nauru", common: "Nauru" },
      rus: { official: "Республика Науру", common: "Науру" },
      slk: { official: "Naurská republika", common: "Nauru" },
      spa: { official: "República de Nauru", common: "Nauru" },
      srp: { official: "Република Науру", common: "Науру" },
      swe: { official: "Republiken Nauru", common: "Nauru" },
      tur: { official: "Nauru Cumhuriyeti", common: "Nauru" },
      urd: { official: "جمہوریہ ناورو", common: "ناورو" },
      zho: { official: "瑙鲁共和国", common: "瑙鲁" },
    },
    latlng: [-0.53333333, 166.91666666],
    landlocked: false,
    area: 21.0,
    demonyms: {
      eng: { f: "Nauruan", m: "Nauruan" },
      fra: { f: "Nauruane", m: "Nauruan" },
    },
    flag: "\uD83C\uDDF3\uD83C\uDDF7",
    maps: {
      googleMaps: "https://goo.gl/maps/kyAGw6XEJgjSMsTK7",
      openStreetMaps: "https://www.openstreetmap.org/relation/571804",
    },
    population: 10834,
    gini: { "2012": 34.8 },
    car: { signs: ["NAU"], side: "left" },
    timezones: ["UTC+12:00"],
    continents: ["Oceania"],
    flags: {
      png: "https://flagcdn.com/w320/nr.png",
      svg: "https://flagcdn.com/nr.svg",
      alt: "The flag of Nauru has a dark blue field with a thin yellow horizontal band across the center and a large white twelve-pointed star beneath the horizontal band on the hoist side of the field.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/nr.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/nr.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [-0.55, 166.92] },
  },
  {
    name: {
      common: "Czechia",
      official: "Czech Republic",
      nativeName: {
        ces: { official: "Česká republika", common: "Česko" },
        slk: { official: "Česká republika", common: "Česko" },
      },
    },
    tld: [".cz"],
    cca2: "CZ",
    ccn3: "203",
    cca3: "CZE",
    cioc: "CZE",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { CZK: { name: "Czech koruna", symbol: "Kč" } },
    idd: { root: "+4", suffixes: ["20"] },
    capital: ["Prague"],
    altSpellings: ["CZ", "Česká republika", "Česko"],
    region: "Europe",
    subregion: "Central Europe",
    languages: { ces: "Czech", slk: "Slovak" },
    translations: {
      ara: { official: "جمهورية التشيك", common: "التشيك" },
      bre: { official: "Republik Tchek", common: "Tchekia" },
      ces: { official: "Česká republika", common: "Česko" },
      cym: {
        official: "Y Weriniaeth Tsiec",
        common: "Y Weriniaeth Tsiec",
      },
      deu: { official: "Tschechische Republik", common: "Tschechien" },
      est: { official: "Tšehhi Vabariik", common: "Tšehhi" },
      fin: { official: "Tšekin tasavalta", common: "Tšekki" },
      fra: { official: "République tchèque", common: "Tchéquie" },
      hrv: { official: "Češka", common: "Češka" },
      hun: { official: "Cseh Köztársaság", common: "Csehország" },
      ita: { official: "Repubblica Ceca", common: "Cechia" },
      jpn: { official: "チェコ共和国", common: "チェコ" },
      kor: { official: "체코", common: "체코" },
      nld: { official: "Tsjechische Republiek", common: "Tsjechië" },
      per: { official: "جمهوری چک", common: "جمهوری چک" },
      pol: { official: "Republika Czeska", common: "Czechy" },
      por: { official: "República Checa", common: "Chéquia" },
      rus: { official: "Чешская Республика", common: "Чехия" },
      slk: { official: "Česká republika", common: "Česko" },
      spa: { official: "República Checa", common: "Chequia" },
      srp: { official: "Чешка Република", common: "Чешка" },
      swe: { official: "Republiken Tjeckien", common: "Tjeckien" },
      tur: { official: "Çek Cumhuriyeti", common: "Çekya" },
      urd: { official: "چيک جمہوريہ", common: "چيک" },
      zho: { official: "捷克共和国", common: "捷克" },
    },
    latlng: [49.75, 15.5],
    landlocked: true,
    borders: ["AUT", "DEU", "POL", "SVK"],
    area: 78865.0,
    demonyms: {
      eng: { f: "Czech", m: "Czech" },
      fra: { f: "Tchèque", m: "Tchèque" },
    },
    flag: "\uD83C\uDDE8\uD83C\uDDFF",
    maps: {
      googleMaps: "https://goo.gl/maps/47dmgeXMZyhDHyQW8",
      openStreetMaps: "https://www.openstreetmap.org/relation/51684",
    },
    population: 10698896,
    gini: { "2018": 25.0 },
    fifa: "CZE",
    car: { signs: ["CZ"], side: "right" },
    timezones: ["UTC+01:00"],
    continents: ["Europe"],
    flags: {
      png: "https://flagcdn.com/w320/cz.png",
      svg: "https://flagcdn.com/cz.svg",
      alt: "The flag of Czechia is composed of two equal horizontal bands of white and red, with a blue isosceles triangle superimposed on the hoist side of the field. The triangle has its base on the hoist end and spans about two-fifth the width of the field.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/cz.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/cz.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [50.08, 14.47] },
    postalCode: { format: "### ##", regex: "^(\\d{5})$" },
  },
  {
    name: {
      common: "Egypt",
      official: "Arab Republic of Egypt",
      nativeName: {
        ara: { official: "جمهورية مصر العربية", common: "مصر" },
      },
    },
    tld: [".eg", ".مصر"],
    cca2: "EG",
    ccn3: "818",
    cca3: "EGY",
    cioc: "EGY",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { EGP: { name: "Egyptian pound", symbol: "£" } },
    idd: { root: "+2", suffixes: ["0"] },
    capital: ["Cairo"],
    altSpellings: ["EG", "Arab Republic of Egypt"],
    region: "Africa",
    subregion: "Northern Africa",
    languages: { ara: "Arabic" },
    translations: {
      ara: { official: "جمهورية مصر العربية", common: "مصر" },
      bre: { official: "Republik arab Egipt", common: "Egipt" },
      ces: { official: "Egyptská arabská republika", common: "Egypt" },
      cym: {
        official: "Gweriniaeth Arabaidd yr Aifft",
        common: "Yr Aifft",
      },
      deu: { official: "Arabische Republik Ägypten", common: "Ägypten" },
      est: { official: "Egiptuse Araabia Vabariik", common: "Egiptus" },
      fin: { official: "Egyptin arabitasavalta", common: "Egypti" },
      fra: { official: "République arabe d'Égypte", common: "Égypte" },
      hrv: { official: "Arapska Republika Egipat", common: "Egipat" },
      hun: { official: "Egyiptomi Arab Köztársaság", common: "Egyiptom" },
      ita: { official: "Repubblica araba d'Egitto", common: "Egitto" },
      jpn: { official: "エジプト·アラブ共和国", common: "エジプト" },
      kor: { official: "이집트 아랍 공화국", common: "이집트" },
      nld: { official: "Arabische Republiek Egypte", common: "Egypte" },
      per: { official: "جمهوری عربی مصر", common: "مصر" },
      pol: { official: "Arabska Republika Egiptu", common: "Egipt" },
      por: { official: "República Árabe do Egipto", common: "Egito" },
      rus: { official: "Арабская Республика Египет", common: "Египет" },
      slk: { official: "Egyptská arabská republika", common: "Egypt" },
      spa: { official: "República Árabe de Egipto", common: "Egipto" },
      srp: { official: "Арапска Република Египат", common: "Египат" },
      swe: { official: "Arabrepubliken Egypten", common: "Egypten" },
      tur: { official: "Mısır Arap Cumhuriyeti", common: "Mısır" },
      urd: { official: "مصری عرب جمہوریہ", common: "مصر" },
      zho: { official: "阿拉伯埃及共和国", common: "埃及" },
    },
    latlng: [27.0, 30.0],
    landlocked: false,
    borders: ["ISR", "LBY", "PSE", "SDN"],
    area: 1002450.0,
    demonyms: {
      eng: { f: "Egyptian", m: "Egyptian" },
      fra: { f: "Égyptienne", m: "Égyptien" },
    },
    flag: "\uD83C\uDDEA\uD83C\uDDEC",
    maps: {
      googleMaps: "https://goo.gl/maps/uoDRhXbsqjG6L7VG7",
      openStreetMaps: "https://www.openstreetmap.org/relation/1473947",
    },
    population: 102334403,
    gini: { "2017": 31.5 },
    fifa: "EGY",
    car: { signs: ["ET"], side: "right" },
    timezones: ["UTC+02:00"],
    continents: ["Africa"],
    flags: {
      png: "https://flagcdn.com/w320/eg.png",
      svg: "https://flagcdn.com/eg.svg",
      alt: "The flag of Egypt is composed of three equal horizontal bands of red, white and black, with Egypt's national emblem — a hoist-side facing gold eagle of Saladin — centered in the white band.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/eg.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/eg.svg",
    },
    startOfWeek: "sunday",
    capitalInfo: { latlng: [30.05, 31.25] },
    postalCode: { format: "#####", regex: "^(\\d{5})$" },
  },
  {
    name: {
      common: "Myanmar",
      official: "Republic of the Union of Myanmar",
      nativeName: {
        mya: {
          official: "ပြည်ထောင်စု သမ္မတ မြန်မာနိုင်ငံတော်",
          common: "မြန်မာ",
        },
      },
    },
    tld: [".mm"],
    cca2: "MM",
    ccn3: "104",
    cca3: "MMR",
    cioc: "MYA",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { MMK: { name: "Burmese kyat", symbol: "Ks" } },
    idd: { root: "+9", suffixes: ["5"] },
    capital: ["Naypyidaw"],
    altSpellings: [
      "MM",
      "Burma",
      "Republic of the Union of Myanmar",
      "Pyidaunzu Thanmăda Myăma Nainngandaw",
    ],
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: { mya: "Burmese" },
    translations: {
      ara: { official: "جمهورية اتحاد ميانمار", common: "ميانمار" },
      bre: { official: "Republik Unaniezh Myanmar", common: "Myanmar" },
      ces: { official: "Republika Myanmarský svaz", common: "Myanmar" },
      cym: {
        official: "Republic of the Union of Myanmar",
        common: "Myanmar",
      },
      deu: { official: "Republik der Union Myanmar", common: "Myanmar" },
      est: { official: "Myanmari Liidu Vabariik", common: "Myanmar" },
      fin: { official: "Myanmarin liiton tasavalta", common: "Myanmar" },
      fra: {
        official: "République de l'Union du Myanmar",
        common: "Birmanie",
      },
      hrv: { official: "Republika Unije Mijanmar", common: "Mijanmar" },
      hun: {
        official: "Mianmari Államszövetség Köztársasága",
        common: "Mianmar",
      },
      ita: {
        official: "Repubblica dell'Unione di Myanmar",
        common: "Birmania",
      },
      jpn: { official: "ミャンマー連邦共和国", common: "ミャンマー" },
      kor: { official: "미얀마 연방 공화국", common: "미얀마" },
      nld: {
        official: "Republiek van de Unie van Myanmar",
        common: "Myanmar",
      },
      per: { official: "اتحادیه جمهوری میانمار", common: "میانمار" },
      pol: { official: "Republika Związku Mjanmy", common: "Mjanma" },
      por: {
        official: "República da União de Myanmar",
        common: "Myanmar",
      },
      rus: { official: "Республика Союза Мьянма", common: "Мьянма" },
      slk: {
        official: "Mjanmarská zväzová republika",
        common: "Mjanmarsko",
      },
      spa: {
        official: "República de la Unión de Myanmar",
        common: "Myanmar",
      },
      srp: { official: "Република Савез Мјанмара", common: "Мјанмар" },
      swe: { official: "Republiken Unionen Myanmar", common: "Myanmar" },
      tur: { official: "Myanmar Birliği Cumhuriyeti", common: "Myanmar" },
      urd: { official: "متحدہ جمہوریہ میانمار", common: "میانمار" },
      zho: { official: "缅甸联邦共和国", common: "缅甸" },
    },
    latlng: [22.0, 98.0],
    landlocked: false,
    borders: ["BGD", "CHN", "IND", "LAO", "THA"],
    area: 676578.0,
    demonyms: {
      eng: { f: "Burmese", m: "Burmese" },
      fra: { f: "Birmane", m: "Birman" },
    },
    flag: "\uD83C\uDDF2\uD83C\uDDF2",
    maps: {
      googleMaps: "https://goo.gl/maps/4jrZyJkDERUfHyp26",
      openStreetMaps: "https://www.openstreetmap.org/relation/50371",
    },
    population: 54409794,
    gini: { "2017": 30.7 },
    fifa: "MYA",
    car: { signs: ["BUR"], side: "right" },
    timezones: ["UTC+06:30"],
    continents: ["Asia"],
    flags: {
      png: "https://flagcdn.com/w320/mm.png",
      svg: "https://flagcdn.com/mm.svg",
      alt: "The flag of Myanmar is composed of three equal horizontal bands of yellow, green and red, with a large five-pointed white star superimposed at the center of the field.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/mm.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/mm.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [19.76, 96.07] },
    postalCode: { format: "#####", regex: "^(\\d{5})$" },
  },
  {
    name: {
      common: "Netherlands",
      official: "Kingdom of the Netherlands",
      nativeName: {
        nld: {
          official: "Koninkrijk der Nederlanden",
          common: "Nederland",
        },
      },
    },
    tld: [".nl"],
    cca2: "NL",
    ccn3: "528",
    cca3: "NLD",
    cioc: "NED",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    idd: { root: "+3", suffixes: ["1"] },
    capital: ["Amsterdam"],
    altSpellings: ["NL", "Holland", "Nederland", "The Netherlands"],
    region: "Europe",
    subregion: "Western Europe",
    languages: { nld: "Dutch" },
    translations: {
      ara: { official: "مملكة هولندا", common: "هولندا" },
      bre: {
        official: "Rouantelezh an Izelvroioù",
        common: "Izelvroioù",
      },
      ces: { official: "Nizozemské království", common: "Nizozemsko" },
      cym: {
        official: "Kingdom of the Netherlands",
        common: "Netherlands",
      },
      deu: { official: "Niederlande", common: "Niederlande" },
      est: { official: "Madalmaade Kuningriik", common: "Holland" },
      fin: { official: "Alankomaat", common: "Alankomaat" },
      fra: { official: "Pays-Bas", common: "Pays-Bas" },
      hrv: { official: "Holandija", common: "Nizozemska" },
      hun: { official: "Holland Királyság", common: "Hollandia" },
      ita: { official: "Paesi Bassi", common: "Paesi Bassi" },
      jpn: { official: "オランダ", common: "オランダ" },
      kor: { official: "네덜란드 왕국", common: "네덜란드" },
      nld: { official: "Nederland", common: "Nederland" },
      per: { official: "هلند", common: "هلند" },
      pol: { official: "Królestwo Niderlandów", common: "Holandia" },
      por: { official: "Holanda", common: "Holanda" },
      rus: { official: "Нидерланды", common: "Нидерланды" },
      slk: { official: "Holandské kráľovstvo", common: "Holansko" },
      spa: { official: "Países Bajos", common: "Países Bajos" },
      srp: { official: "Краљевина Холандија", common: "Холандија" },
      swe: { official: "Nederländerna", common: "Nederländerna" },
      tur: { official: "Hollanda", common: "Hollanda" },
      urd: { official: "مملکتِ نیدرلینڈز", common: "نیدرلینڈز" },
      zho: { official: "荷兰", common: "荷兰" },
    },
    latlng: [52.5, 5.75],
    landlocked: false,
    borders: ["BEL", "DEU"],
    area: 41850.0,
    demonyms: {
      eng: { f: "Dutch", m: "Dutch" },
      fra: { f: "Néerlandaise", m: "Néerlandais" },
    },
    flag: "\uD83C\uDDF3\uD83C\uDDF1",
    maps: {
      googleMaps: "https://goo.gl/maps/Hv6zQswGhFxoVVBm6",
      openStreetMaps: "https://www.openstreetmap.org/relation/47796",
    },
    population: 16655799,
    gini: { "2018": 28.1 },
    fifa: "NED",
    car: { signs: ["NL"], side: "right" },
    timezones: ["UTC+01:00"],
    continents: ["Europe"],
    flags: {
      png: "https://flagcdn.com/w320/nl.png",
      svg: "https://flagcdn.com/nl.svg",
      alt: "The flag of the Netherlands is composed of three equal horizontal bands of red, white and blue.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/nl.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/nl.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [52.35, 4.92] },
    postalCode: { format: "#### @@", regex: "^(\\d{4}[A-Z]{2})$" },
  },
  {
    name: {
      common: "Uruguay",
      official: "Oriental Republic of Uruguay",
      nativeName: {
        spa: {
          official: "República Oriental del Uruguay",
          common: "Uruguay",
        },
      },
    },
    tld: [".uy"],
    cca2: "UY",
    ccn3: "858",
    cca3: "URY",
    cioc: "URU",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { UYU: { name: "Uruguayan peso", symbol: "$" } },
    idd: { root: "+5", suffixes: ["98"] },
    capital: ["Montevideo"],
    altSpellings: [
      "UY",
      "Oriental Republic of Uruguay",
      "República Oriental del Uruguay",
    ],
    region: "Americas",
    subregion: "South America",
    languages: { spa: "Spanish" },
    translations: {
      ara: {
        official: "جمهورية الأوروغواي الشرقية",
        common: "الأوروغواي",
      },
      bre: { official: "Republik Reter Uruguay", common: "Uruguay" },
      ces: {
        official: "Uruguayská východní republika",
        common: "Uruguay",
      },
      cym: {
        official: "Oriental Republic of Uruguay",
        common: "Uruguay",
      },
      deu: {
        official: "Republik Östlich des Uruguay",
        common: "Uruguay",
      },
      est: { official: "Uruguay Idavabariik", common: "Uruguay" },
      fin: { official: "Uruguayn itäinen tasavalta", common: "Uruguay" },
      fra: {
        official: "République orientale de l'Uruguay",
        common: "Uruguay",
      },
      hrv: {
        official: "Orijentalna Republika Urugvaj",
        common: "Urugvaj",
      },
      hun: { official: "Uruguayi Keleti Köztársaság", common: "Uruguay" },
      ita: {
        official: "Repubblica Orientale dell'Uruguay",
        common: "Uruguay",
      },
      jpn: { official: "ウルグアイ東方共和国", common: "ウルグアイ" },
      kor: { official: "우루과이 동방 공화국", common: "우루과이" },
      nld: { official: "Oosterse Republiek Uruguay", common: "Uruguay" },
      per: { official: "جمهوری اروگوئه", common: "اروگوئه" },
      pol: {
        official: "Wschodnia Republika Urugwaju",
        common: "Urugwaj",
      },
      por: {
        official: "República Oriental do Uruguai",
        common: "Uruguai",
      },
      rus: {
        official: "Восточной Республики Уругвай",
        common: "Уругвай",
      },
      slk: {
        official: "Uruguajská východná republika",
        common: "Uruguaj",
      },
      spa: {
        official: "República Oriental del Uruguay",
        common: "Uruguay",
      },
      srp: { official: "Источна Република Уругвај", common: "Уругвај" },
      swe: { official: "Republiken Uruguay", common: "Uruguay" },
      tur: { official: "Uruguay Doğu Cumhuriyeti", common: "Uruguay" },
      urd: { official: "جمہوریہ شرقیہ یوراگوئے", common: "یوراگوئے" },
      zho: { official: "乌拉圭东岸共和国", common: "乌拉圭" },
    },
    latlng: [-33.0, -56.0],
    landlocked: false,
    borders: ["ARG", "BRA"],
    area: 181034.0,
    demonyms: {
      eng: { f: "Uruguayan", m: "Uruguayan" },
      fra: { f: "Uruguayenne", m: "Uruguayen" },
    },
    flag: "\uD83C\uDDFA\uD83C\uDDFE",
    maps: {
      googleMaps: "https://goo.gl/maps/tiQ9Baekb1jQtDSD9",
      openStreetMaps: "https://www.openstreetmap.org/relation/287072",
    },
    population: 3473727,
    gini: { "2019": 39.7 },
    fifa: "URU",
    car: { signs: ["ROU"], side: "right" },
    timezones: ["UTC-03:00"],
    continents: ["South America"],
    flags: {
      png: "https://flagcdn.com/w320/uy.png",
      svg: "https://flagcdn.com/uy.svg",
      alt: "The flag of Uruguay is composed of nine equal horizontal bands of white alternating with blue, with a white square superimposed in the canton. In the white square is a yellow sun bearing a human face — the Sun of May — from which sixteen rays extend. The sun's rays alternate between triangular and wavy.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/uy.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/uy.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [-34.85, -56.17] },
    postalCode: { format: "#####", regex: "^(\\d{5})$" },
  },
  {
    name: {
      common: "Northern Mariana Islands",
      official: "Commonwealth of the Northern Mariana Islands",
      nativeName: {
        cal: {
          official: "Commonwealth of the Northern Mariana Islands",
          common: "Northern Mariana Islands",
        },
        cha: {
          official: "Sankattan Siha Na Islas Mariånas",
          common: "Na Islas Mariånas",
        },
        eng: {
          official: "Commonwealth of the Northern Mariana Islands",
          common: "Northern Mariana Islands",
        },
      },
    },
    tld: [".mp"],
    cca2: "MP",
    ccn3: "580",
    cca3: "MNP",
    independent: false,
    status: "officially-assigned",
    unMember: false,
    currencies: { USD: { name: "United States dollar", symbol: "$" } },
    idd: { root: "+1", suffixes: ["670"] },
    capital: ["Saipan"],
    altSpellings: [
      "MP",
      "Commonwealth of the Northern Mariana Islands",
      "Sankattan Siha Na Islas Mariånas",
    ],
    region: "Oceania",
    subregion: "Micronesia",
    languages: { cal: "Carolinian", cha: "Chamorro", eng: "English" },
    translations: {
      ara: {
        official: "كومونولث جزر ماريانا الشمالية",
        common: "جزر ماريانا الشمالية",
      },
      bre: {
        official: "Kenglad Inizi Mariana an Norzh",
        common: "Inizi Mariana an Norzh",
      },
      ces: {
        official: "Společenství Severních Marian",
        common: "Severní Mariany",
      },
      cym: {
        official: "Commonwealth of the Northern Mariana Islands",
        common: "Northern Mariana Islands",
      },
      deu: {
        official: "Commonwealth der Nördlichen Marianen",
        common: "Nördliche Marianen",
      },
      est: {
        official: "Põhja-Mariaani Ühendus",
        common: "Põhja-Mariaanid",
      },
      fin: { official: "Pohjois-Mariaanit", common: "Pohjois-Mariaanit" },
      fra: {
        official: "Commonwealth des îles Mariannes du Nord",
        common: "Îles Mariannes du Nord",
      },
      hrv: {
        official: "Zajednica je Sjeverni Marijanski otoci",
        common: "Sjevernomarijanski otoci",
      },
      hun: {
        official: "Északi-Mariana-szigetek",
        common: "Északi-Mariana-szigetek",
      },
      ita: {
        official: "Commonwealth delle Isole Marianne Settentrionali",
        common: "Isole Marianne Settentrionali",
      },
      jpn: { official: "北マリアナ諸島", common: "北マリアナ諸島" },
      kor: { official: "북마리아나 제도", common: "북마리아나 제도" },
      nld: {
        official: "Commonwealth van de Noordelijke Marianen",
        common: "Noordelijke Marianeneilanden",
      },
      per: {
        official: "جزایر ماریانای شمالی",
        common: "جزایر ماریانای شمالی",
      },
      pol: {
        official: "Wspólnota Marianów Północnych",
        common: "Mariany Północne",
      },
      por: {
        official: "Comunidade das Ilhas Marianas do Norte",
        common: "Marianas Setentrionais",
      },
      rus: {
        official: "Содружество Северных Марианских островов",
        common: "Северные Марианские острова",
      },
      slk: {
        official: "Spoločenstvo ostrovov Severné Mariány",
        common: "Severné Mariány",
      },
      spa: {
        official: "Mancomunidad de las Islas Marianas del Norte",
        common: "Islas Marianas del Norte",
      },
      srp: {
        official: "Комонвелт Северна Маријанска Острва",
        common: "Северна Маријанска Острва",
      },
      swe: { official: "Nordmarianerna", common: "Nordmarianerna" },
      tur: {
        official: "Kuzey Mariana Adaları Milletler Topluluğu",
        common: "Kuzey Mariana Adaları",
      },
      urd: {
        official: "دولتِ مشترکہ جزائر شمالی ماریانا",
        common: "جزائر شمالی ماریانا",
      },
      zho: { official: "北马里亚纳群岛", common: "北马里亚纳群岛" },
    },
    latlng: [15.2, 145.75],
    landlocked: false,
    area: 464.0,
    demonyms: {
      eng: { f: "American", m: "American" },
      fra: { f: "Américaine", m: "Américan" },
    },
    flag: "\uD83C\uDDF2\uD83C\uDDF5",
    maps: {
      googleMaps: "https://goo.gl/maps/cpZ67knoRAcfu1417",
      openStreetMaps: "https://www.openstreetmap.org/relation/306004",
    },
    population: 57557,
    car: { signs: ["USA"], side: "right" },
    timezones: ["UTC+10:00"],
    continents: ["Oceania"],
    flags: {
      png: "https://flagcdn.com/w320/mp.png",
      svg: "https://flagcdn.com/mp.svg",
    },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [15.2, 145.75] },
  },
];
